# Generated by Django 4.2.8 on 2023-12-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Пункт в анкете')),
                ('number', models.PositiveIntegerField(verbose_name='Номер в анкете')),
                ('type_point', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('check_box', 'check_box'), ('raiting', 'raiting'), ('text_or_non', 'text_or_non')], max_length=12, verbose_name='Тип вопросов')),
                ('num_column', models.SmallIntegerField(verbose_name='Кол-во колонок')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название опроса')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Начало анкетирования')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Окончание анкетирования')),
                ('finished', models.BooleanField(default=False, verbose_name='Окончен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaries', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('number', models.PositiveIntegerField(verbose_name='Номер в пункте')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.point', verbose_name='Пункт в Анкете')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='point',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='questionnaire.questionnaire'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaire.question')),
            ],
        ),
    ]
