# Generated by Django 4.2.8 on 2023-12-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderCloumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Заголовок колонки')),
                ('num_col', models.PositiveIntegerField(verbose_name='Номер по порядку')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='questionnaire.headercloumn')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='questionnaire.point')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='header_cloumn',
            field=models.ManyToManyField(related_name='header_column', through='questionnaire.HeaderPoint', to='questionnaire.headercloumn'),
        ),
    ]
