# Generated by Django 4.2.8 on 2023-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
